name: Salesforce Delta Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Install SFDX-Git-Delta Plugin
        run: echo "y" | sf plugins install sfdx-git-delta

      - name: Create server.key
        run: |
          mkdir -p assets
          echo "${{ secrets.JWT_KEY }}" | base64 --decode > assets/server.key

      - name: Authenticate Salesforce Org
        run: |
          sf org login jwt \
            --client-id ${{ secrets.CLIENT_ID }} \
            --jwt-key-file assets/server.key \
            --username ${{ secrets.SF_USERNAME_UAT }} \
            --instance-url https://login.salesforce.com \
            --alias HUH

      - name: Generate the package.xml for delta files
        id: generate-delta-files
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mkdir delta
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output "./delta" --ignore-whitespace -d -i .sgdignore
          echo "--- package.xml generated with added and modified metadata ---"
          cat delta/package/package.xml
          ls delta

      - name: Validate components to Salesforce
        id: validate-pull-request-components
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          sf project deploy validate --manifest delta/package/package.xml --test-level RunLocalTests --target-org HUH --coverage-formatters clover

      #- name: Deploy Delta Components
       # run: |
       #   sf project deploy start --metadata-dir deploy_package --post-destructive-changes deploy_package/destructiveChanges.xml --test-level RunLocalTests --target-org HUH --wait 120 --verbose
